# -*- coding: utf-8 -*-
"""housing affordability by HSA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C5K16ScWy4OYPh0yPFwW-tP1l_3LmKW2
"""

import pandas as pd
import geopandas as gpd
import json
import requests
import numpy as np
import folium
import re

# ── Load data ─────────────────────────────────────────────────────────────────
import os

# Get the directory where the script is located
BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# Update the paths to look inside a 'data' subfolder
df = pd.read_excel(os.path.join(BASE_DIR, 'data', 'HOAM_CBSA_Data.xlsx'))
geo_df = gpd.read_file(os.path.join(BASE_DIR, 'data', 'NTAD_Core_Based_Statistical_Areas_-3212212215612359570', 'Core_Based_Statistical_Areas.shp'))
states_df = gpd.read_file(os.path.join(BASE_DIR, 'data', 'cb_2018_us_state_20m', 'cb_2018_us_state_20m.shp'))


df['Month'] = pd.to_datetime(df['Month'])
df['Year'] = df['Month'].dt.year
df['CBSA_Code'] = df['CBSA_Code'].astype(str).str.zfill(5)
geo_df['GEOID'] = geo_df['GEOID'].astype(str).str.zfill(5)

METRIC = 'Housing_Cost%_of_Med_HHIncome'
CENSUS_YEAR = 2022   # ACS 5-year vintage used for demographics
# ── Census demographics ───────────────────────────────────────────────────────
def fetch_census_cbsa():
    url = (
        "https://api.census.gov/data/2022/acs/acs5"
        "?get=NAME,B01003_001E,B19013_001E"
        "&for=metropolitan+statistical+area/micropolitan+statistical+area:*"
    )
    try:
        r = requests.get(url, timeout=15)
        data = r.json()
        cdf = pd.DataFrame(data[1:], columns=data[0])
        cdf = cdf.rename(columns={
            'metropolitan statistical area/micropolitan statistical area': 'CBSA_Code',
            'B01003_001E': 'Population',
            'B19013_001E': 'Median_HH_Income',
        })
        cdf['CBSA_Code'] = cdf['CBSA_Code'].str.zfill(5)
        cdf['Population'] = pd.to_numeric(cdf['Population'], errors='coerce')
        cdf['Median_HH_Income'] = pd.to_numeric(cdf['Median_HH_Income'], errors='coerce')
        return cdf[['CBSA_Code', 'Population', 'Median_HH_Income']]
    except Exception as e:
        print(f"Census fetch failed: {e}")
        return pd.DataFrame(columns=['CBSA_Code', 'Population', 'Median_HH_Income'])

census = fetch_census_cbsa()

# ── Yearly aggregate ──────────────────────────────────────────────────────────
df_yearly = df.groupby(['CBSA_Code', 'CBSA_Name', 'Year'], as_index=False)[METRIC].mean()
df_yearly[METRIC] = df_yearly[METRIC]#.round(1)
df_yearly['Rank'] = df_yearly.groupby('Year')[METRIC].rank(method='min', ascending=True).astype(int)
df_yearly['N_MSAs'] = df_yearly.groupby('Year')['CBSA_Code'].transform('count')

# ── Cross-time stats ──────────────────────────────────────────────────────────
def cross_stats(g):
    best_idx  = g[METRIC].idxmin()
    worst_idx = g[METRIC].idxmax()
    return pd.Series({
        'Avg_Cost_Pct':   round(g[METRIC].mean(), 1),
        'Best_Year':      f"{int(g.loc[best_idx,  'Year'])} (#{int(g.loc[best_idx,  'Rank'])} of {int(g.loc[best_idx,  'N_MSAs'])})",
        'Best_Cost_Raw':  g.loc[best_idx,  METRIC],
        'Worst_Year':     f"{int(g.loc[worst_idx, 'Year'])} (#{int(g.loc[worst_idx, 'Rank'])} of {int(g.loc[worst_idx, 'N_MSAs'])})",
        'Worst_Cost_Raw': g.loc[worst_idx, METRIC],
    })

try:
    cross_time = df_yearly.groupby('CBSA_Code').apply(cross_stats, include_groups=False)
except TypeError:
    cross_time = df_yearly.groupby('CBSA_Code').apply(cross_stats)

cross_time = cross_time.reset_index()  # CBSA_Code becomes a column
df_yearly = df_yearly.merge(cross_time, on='CBSA_Code')

if not census.empty:
    df_yearly = df_yearly.merge(census, on='CBSA_Code', how='left')
    df_yearly['Pop_Display'] = df_yearly['Population'].apply(
        lambda x: f"{x/1e6:.2f}M" if pd.notna(x) and x >= 1e6 else (f"{x/1e3:.0f}K" if pd.notna(x) else "N/A"))
    df_yearly['Income_Display'] = df_yearly['Median_HH_Income'].apply(
        lambda x: f"${x:,.0f}" if pd.notna(x) else "N/A")
else:
    df_yearly['Pop_Display'] = 'N/A'
    df_yearly['Income_Display'] = 'N/A'

# ── Geometry ──────────────────────────────────────────────────────────────────
geo_df = geo_df.to_crs(epsg=4326)
geo_df['geometry'] = geo_df['geometry'].simplify(0.05, preserve_topology=True)
states_df = states_df.to_crs(epsg=4326)

cbsa_codes = df_yearly['CBSA_Code'].unique()
geo_slim = geo_df[geo_df['GEOID'].isin(cbsa_codes)][['GEOID', 'geometry']].copy()

print(f"✅ Data ready — {len(cbsa_codes)} MSAs, years {df_yearly['Year'].min()}–{df_yearly['Year'].max()}")

# ── Data range ────────────────────────────────────────────────────────────────
sample = df_yearly[METRIC].dropna()
IS_DECIMAL = sample.median() < 1.0
to_pct = lambda v: v * 100 if IS_DECIMAL else v
VMIN = to_pct(float(sample.quantile(0.02)))
VMID = 30.0
VMAX = to_pct(float(sample.quantile(0.98)))
print(f"Display range: {VMIN:.1f}% – {VMAX:.1f}%")

# ── Color function ────────────────────────────────────────────────────────────
def val_to_color(raw_val):
    if raw_val is None or (isinstance(raw_val, float) and np.isnan(raw_val)):
        return '#cccccc'
    val = max(VMIN, min(VMAX, to_pct(raw_val)))
    if val <= VMID:
        t = (val - VMIN) / max(VMID - VMIN, 0.001)
        return '#{:02x}{:02x}{:02x}'.format(
            int(26  + (255 - 26)  * t),
            int(152 + (255 - 152) * t),
            int(80  + (191 - 80)  * t))
    else:
        t = (val - VMID) / max(VMAX - VMID, 0.001)
        return '#{:02x}{:02x}{:02x}'.format(
            int(255 + (215 - 255) * t),
            int(255 + (48  - 255) * t),
            int(191 + (39  - 191) * t))

# ── Build JS data ─────────────────────────────────────────────────────────────
js_data = {}
for yr, grp in df_yearly.groupby('Year'):
    js_data[int(yr)] = {}
    for _, row in grp.iterrows():
        mv = row[METRIC]
        js_data[int(yr)][row['CBSA_Code']] = {
            'metric':      round(to_pct(mv), 1) if pd.notna(mv) else None,
            'rank':        int(row['Rank']),
            'n_msas':      int(row['N_MSAs']),
            'name':        row['CBSA_Name'],
            'avg_cost':    round(to_pct(row['Avg_Cost_Pct']), 1),
            'best_year':   str(row['Best_Year']),
            'best_cost':   round(to_pct(row['Best_Cost_Raw']),  1) if pd.notna(row['Best_Cost_Raw'])  else None,
            'worst_year':  str(row['Worst_Year']),
            'worst_cost':  round(to_pct(row['Worst_Cost_Raw']), 1) if pd.notna(row['Worst_Cost_Raw']) else None,
            'population':  str(row['Pop_Display']),
            'income':      str(row['Income_Display']),
            'color':       val_to_color(mv),
        }

years_list = sorted(js_data.keys())
default_year = years_list[-1]

# ── GeoJSON — bake GEOID + initial fill color into every feature ──────────────
base_geojson = json.loads(geo_slim.to_json())
latest = js_data[default_year]

for feat in base_geojson['features']:
    geoid = str(feat['properties'].get('GEOID', '')).zfill(5)
    feat['properties']['GEOID'] = geoid
    d = latest.get(geoid, {})
    feat['properties']['fillColor'] = d.get('color', '#cccccc')

# ── Folium map ────────────────────────────────────────────────────────────────
# Updated Map Initialization with Sources
m = folium.Map(
    location=[38.5, -96],
    zoom_start=4,
    tiles='https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png',
    attr='&copy; <a href="https://www.atlantafed.org/research-and-data/data/home-ownership-affordability-monitor">Atlanta Fed HOAM</a> | &copy; <a href="https://www.census.gov/">U.S. Census Bureau</a>'
)

gjson = folium.GeoJson(
    base_geojson,
    name='msas',
    style_function=lambda f: {
        'fillColor':   f['properties'].get('fillColor', '#cccccc'),
        'color':       'white',
        'weight':      0.4,
        'fillOpacity': 0.85,
    },
    highlight_function=lambda f: {
        'color': '#333', 'weight': 2, 'fillOpacity': 0.95,
    },
).add_to(m)

states_geojson = json.loads(states_df.to_json())
folium.GeoJson(
    states_geojson,
    name='states',
    style_function=lambda f: {
        'fillColor':   'none',
        'color':       '#555555',
        'weight':      1.2,
        'fillOpacity': 0,
    },
).add_to(m)

# ── Render and extract Folium variable names ──────────────────────────────────
html_str = m.get_root().render()
map_var   = re.search(r'var (map_[a-f0-9]+) =', html_str).group(1)
layer_var = re.search(r'var (geo_json_[a-f0-9]+) =', html_str).group(1)

# ── Injection block ───────────────────────────────────────────────────────────
inject = f"""
<style>
#year-ctrl {{
  position:fixed; bottom:28px; left:50%; transform:translateX(-50%);
  z-index:9999; background:white; padding:10px 24px 8px;
  border-radius:25px; border:1px solid #ccc;
  box-shadow:2px 2px 10px rgba(0,0,0,.2);
  font-family:Arial,sans-serif; font-size:13px; text-align:center; min-width:360px;
}}
#year-ctrl label {{ font-weight:bold; margin-right:10px; }}
#year-slider {{ width:230px; vertical-align:middle; cursor:pointer; accent-color:#1565c0; }}
#year-val {{ font-weight:bold; color:#1565c0; margin-left:10px; font-size:16px;
             display:inline-block; min-width:40px; }}
#legend {{
  position:fixed; bottom:95px; left:20px; z-index:9999;
  background:white; padding:10px 14px; border-radius:6px;
  border:1px solid #ccc; box-shadow:2px 2px 8px rgba(0,0,0,.15);
  font-family:Arial,sans-serif; font-size:11px; min-width:200px;
}}
#tip {{
  position:fixed; z-index:99999; background:white;
  padding:11px 15px; border-radius:7px; border:1px solid #ddd;
  box-shadow:3px 3px 12px rgba(0,0,0,.18);
  font-family:Arial,sans-serif; font-size:12px; line-height:1.8;
  pointer-events:none; display:none; width:320px;
}}
#map-title {{
  position:fixed; top:12px; left:50%; transform:translateX(-50%);
  z-index:9999; background:white; padding:6px 22px; border-radius:20px;
  border:1px solid #ddd; font-family:Arial; font-size:14px; font-weight:bold;
  box-shadow:1px 1px 6px rgba(0,0,0,.15); white-space:nowrap;
}}
#data-source {{
  position:fixed; bottom:15px; right:10px; z-index:9999;
  background:rgba(255, 255, 255, 0.7); padding:4px 8px; border-radius:4px;
  font-family:Arial,sans-serif; font-size:10px; color:#555;
  pointer-events: auto;
}}
#data-source a {{ color: #1565c0; text-decoration: none; }}
</style>

<div id="map-title">MSA Housing Cost as % of Median HH Income</div>
<div id="year-ctrl">
  <label>Year:</label>
  <input type="range" id="year-slider"
    min="{years_list[0]}" max="{years_list[-1]}" step="1" value="{default_year}">
  <span id="year-val">{default_year}</span>
</div>
<div id="legend">
  <b>Housing Cost % of Income</b><br>
  <div style="margin:7px 0 3px; height:13px; border-radius:3px;
    background:linear-gradient(to right,#1a9850,#ffffbf,#d73027);"></div>
  <div style="display:flex; justify-content:space-between; font-size:10px; color:#666;">
    <span>{VMIN:.0f}%</span><span>30% baseline</span><span>{VMAX:.0f}%</span>
  </div>
  <div style="display:flex; justify-content:space-between; font-size:10px; color:#999; margin-top:2px;">
    <span>affordable</span><span></span><span>unaffordable</span>
  </div>
</div>
<div id="tip"></div>
<div id="data-source">
  Sources: <a href="https://www.atlantafed.org/research-and-data/data/home-ownership-affordability-monitor" target="_blank">Atlanta Fed HOAM Index</a>,
  <a href="https://www.census.gov/" target="_blank">U.S. Census Bureau (ACS)</a>
</div>
<script>
var _map   = {map_var};
var _layer = {layer_var};
var DATA   = {json.dumps(js_data)};
var YEARS  = {years_list};
var curYear = {default_year};
var tip = document.getElementById('tip');

function fmt(v) {{ return v != null ? v + '%' : 'N/A'; }}

// Computes drawing coordinates for a line chart and returns an SVG image
function makeSparkline(geoid, currentYear) {{
    var validData = [];
    var minVal = Infinity, maxVal = -Infinity;

    // Collect data bounds for scaling
    for (var i = 0; i < YEARS.length; i++) {{
        var yr = YEARS[i];
        var d = DATA[yr] && DATA[yr][geoid];
        if (d && d.metric != null) {{
            validData.push({{year: yr, xIndex: i, y: d.metric}});
            if (d.metric < minVal) minVal = d.metric;
            if (d.metric > maxVal) maxVal = d.metric;
        }}
    }}

    // Exit if not enough data to draw a line
    if (validData.length < 2) return '';

    // Drawing area dimensions
    var w = 290, h = 35, pad = 4;
    var rangeY = maxVal - minVal;
    if (rangeY === 0) rangeY = 1;
    var rangeX = YEARS.length - 1;

    var pathData = [];
    var dotHtml = '';

    // Calculate X and Y mapping for each data point
    for (var i = 0; i < validData.length; i++) {{
        var pt = validData[i];
        var cx = pad + (pt.xIndex / rangeX) * (w - pad * 2);
        var cy = h - pad - ((pt.y - minVal) / rangeY) * (h - pad * 2);
        pathData.push(cx + ',' + cy);

        // Add a red circle to pinpoint the currently selected year on the slider
        if (pt.year === currentYear) {{
            dotHtml = '<circle cx="' + cx + '" cy="' + cy + '" r="3.5" fill="#d73027" />';
        }}
    }}

    // Construct the actual line drawing output
    return '<div style="margin-top:10px; padding-top:8px; border-top:1px solid #eee;">' +
           '<div style="font-size:10px; color:#777; margin-bottom:2px;">Trend (' + YEARS[0] + ' - ' + YEARS[YEARS.length-1] + ')</div>' +
           '<svg width="' + w + '" height="' + h + '" style="overflow:visible;">' +
           '<polyline points="' + pathData.join(' ') + '" fill="none" stroke="#1565c0" stroke-width="2" />' +
           dotHtml +
           '</svg></div>';
}}

function tooltipHTML(d, yr, geoid) {{
  if (!d) return '<i style="color:#999">No data</i>';
  var baseHtml = '<b style="font-size:13px">' + d.name + '</b>' +
    '<div style="border-top:1px solid #eee;margin:5px 0 4px"></div>' +
    '<b>' + yr + '</b><br>' +
    'Housing Cost: <b>' + fmt(d.metric) + '</b>' +
    '&nbsp;&nbsp;Rank: <b>#' + d.rank + '</b> / ' + d.n_msas +
    '<div style="border-top:1px solid #eee;margin:5px 0 4px"></div>' +
    '<b>All-Time</b><br>' +
    'Avg: ' + fmt(d.avg_cost) + '<br>' +
    'Best:&nbsp; ' + d.best_year  + ' &mdash; <b>' + fmt(d.best_cost)  + '</b><br>' +
    'Worst: ' + d.worst_year + ' &mdash; <b>' + fmt(d.worst_cost) + '</b>' +
    '<div style="border-top:1px solid #eee;margin:5px 0 4px"></div>' +
    '<b>Demographics</b> <span style="font-size:10px;color:#999;">({CENSUS_YEAR} ACS)</span><br>' +
    'Population: ' + d.population + '<br>' +
    'Med Income: ' + d.income;

    // Append the line chart
    return baseHtml + makeSparkline(geoid, yr);
}}

function updateColors(year) {{
  curYear = year;
  var yd = DATA[String(year)] || {{}};
  _layer.eachLayer(function(l) {{
    var geoid = l.feature && l.feature.properties && l.feature.properties.GEOID;
    var d = geoid ? yd[geoid] : null;
    l.setStyle({{
      fillColor:   d ? d.color : '#cccccc',
      fillOpacity: d ? 0.85 : 0.25,
    }});
  }});
}}

_layer.eachLayer(function(l) {{
  l.on('mouseover', function(e) {{
    var geoid = l.feature.properties.GEOID;
    var d = (DATA[String(curYear)] || {{}})[geoid];
    tip.innerHTML = tooltipHTML(d, curYear, geoid);
    tip.style.display = 'block';
    l.setStyle({{color:'#333', weight:2, fillOpacity:.95}});
  }});
  l.on('mousemove', function(e) {{
    tip.style.left = (e.originalEvent.clientX + 16) + 'px';
    tip.style.top  = (e.originalEvent.clientY + 10) + 'px';
  }});
  l.on('mouseout', function() {{
    tip.style.display = 'none';
    var geoid = l.feature && l.feature.properties && l.feature.properties.GEOID;
    var d = geoid ? (DATA[String(curYear)] || {{}})[geoid] : null;
    l.setStyle({{
      color:       'white',
      weight:      0.4,
      fillColor:   d ? d.color : '#cccccc',
      fillOpacity: d ? 0.85 : 0.25,
    }});
  }});
}});

document.getElementById('year-slider').addEventListener('input', function() {{
  var yr = parseInt(this.value);
  document.getElementById('year-val').textContent = yr;
  updateColors(yr);
}});

updateColors(curYear);
</script>
"""

html_str = html_str.replace('</html>', inject + '\n</html>')
# Update the output path to 'index.html' so it works with GitHub Pages
out_path = os.path.join(BASE_DIR, 'index.html')

with open(out_path, 'w') as f:
    f.write(html_str)
print(f"Saved → {out_path}")